#
# Copyright (c) 2018-2022, Regents of the University of Minnesota. All rights
# reserved.
#
# This software may be distributed as-is, without modification.
#
ARG IMAGE_INSTALL

FROM ${IMAGE_INSTALL} AS install

# Import all sys-level libs/utils
FROM ubuntu:22.04

